CREATE DATABASE Rainforest
GO
USE Rainforest
GO


CREATE TABLE TCity(
	cZip_code CHAR(4) NOT NULL,
	cCity VARCHAR(100) NOT NULL,
	PRIMARY KEY(cZip_code)	
)

CREATE TABLE TUser(
	iUser_id int IDENTITY NOT NULL,
	cEmail VARCHAR(100) UNIQUE NOT NULL,
	cFirst_name VARCHAR(100) NOT NULL,
	cLast_name VARCHAR(100) NOT NULL,
	cAddress VARCHAR(100) NOT NULL,
	cZip_code CHAR(4) NOT NULL,
	cPhone_no CHAR(8) NOT NULL,
	fTotal_paid MONEY,
	PRIMARY KEY(cEmail),
	FOREIGN KEY(cZip_code) REFERENCES TCity,
	/*
	dBegin DATETIME2 (2) GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETUTCDATE(), 
	dEnd DATETIME2 (2) GENERATED ALWAYS AS ROW END DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME(dBegin, dEnd))
	WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.TUser_History)
	*/
	);


CREATE TABLE TProduct(
	iProduct_id INT IDENTITY NOT NULL,
	cName VARCHAR(100) NOT NULL,
	cDescription varchar(1400) NOT NULL,
	fUnit_price SMALLMONEY NOT NULL,
	fAverage_rating numeric(3,2)
	PRIMARY KEY(iProduct_id),
	/*
	dBegin DATETIME2 (2) GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETUTCDATE(), 
	dEnd DATETIME2 (2) GENERATED ALWAYS AS ROW END DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME(dBegin, dEnd))
	WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.TProduct_History)
	*/
	);

CREATE TABLE TRating(
	iProduct_id INT NOT NULL,
	cEmail VARCHAR(100) NOT NULL,
	iRating NUMERIC(1,0) NOT NULL,
	cComment VARCHAR(1400),
	PRIMARY KEY(iProduct_id, cEmail),
	FOREIGN KEY(iProduct_id) REFERENCES TProduct,
	FOREIGN KEY(cEmail) REFERENCES TUser,
	/*
	dBegin DATETIME2 (2) GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETUTCDATE(), 
	dEnd DATETIME2 (2) GENERATED ALWAYS AS ROW END DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME(dBegin, dEnd))
	WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.TRating_History)*/
	);

CREATE TABLE TCreditCard(
	--check credit card length IN DENMARK
	cCredit_card_no CHAR(16) NOT NULL,
	cEmail VARCHAR(100) NOT NULL,
	cCardholder_name VARCHAR(200),
	cExpiration DATE NOT NULL,
	cCCV NUMERIC(3,0) NOT NULL,
	PRIMARY KEY(cCredit_card_no),
	FOREIGN KEY(cEmail) REFERENCES TUser,
	/*
	dBegin DATETIME2 (2) GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETUTCDATE(), 
	dEnd DATETIME2 (2) GENERATED ALWAYS AS ROW END DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME(dBegin, dEnd))
	WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.TCreditCard_History)
	*/
	);

CREATE TABLE TInvoice(
	iInvoice_id INT IDENTITY NOT NULL,
	dDate DATETIME2 NOT NULL,
	iVat NUMERIC(2,0) NOT NULL,
	fTotal_price MONEY NOT NULL,
	cEmail VARCHAR(100) NOT NULL,
	cCredit_card_no CHAR(16) NOT NULL,
	PRIMARY KEY(iInvoice_id),
	FOREIGN KEY(cEmail) REFERENCES TUser,
	FOREIGN KEY(cCredit_card_no) REFERENCES TCreditCard,
	/*
	dBegin DATETIME2 (2) GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETUTCDATE(), 
	dEnd DATETIME2 (2) GENERATED ALWAYS AS ROW END DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME(dBegin, dEnd))
	WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.TInvoice_History)
	*/
	);

CREATE TABLE TInvoice_line(
	iInvoice_line_id INT IDENTITY NOT NULL,
	iProduct_id INT NOT NULL,
	iInvoice_id INT NOT NULL,
	fPrice SMALLMONEY NOT NULL,
	iQuantity INT NOT NULL,
	PRIMARY KEY(iInvoice_line_id),
	FOREIGN KEY(iProduct_id) REFERENCES TProduct,
	FOREIGN KEY(iInvoice_id) REFERENCES TInvoice,
	/*
	dBegin DATETIME2 (2) GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETUTCDATE(), 
	dEnd DATETIME2 (2) GENERATED ALWAYS AS ROW END DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME(dBegin, dEnd))
	WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.TInvoice_ine_History)
	*/
	);