USE Rainforest
GO

ALTER TABLE TProduct
	ADD 
	dBegin DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETUTCDATE(), 
	dEnd DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME (dBegin, dEnd);

ALTER TABLE TProduct
	SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.TProduct_History))


ALTER TABLE TRating
	ADD 
	dBegin DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN DEFAULT GETUTCDATE(), 
	dEnd DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME (dBegin, dEnd);

ALTER TABLE TRating
	SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.TRating_History))